name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Pull from Repo
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e
            cd /home/ubuntu/Spring-AI-RAG-Chatbot-Ollama-Chroma
            echo "Inside Dir."
            git pull
            echo "Pulled From the Repo"

      - name: Restart Docker container on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e
            cd /home/ubuntu/Spring-AI-RAG-Chatbot-Ollama-Chroma
            echo "Stopping old container..."
            docker compose down
            echo "Rebuilding docker image..."
            docker compose up -d --build
            echo "âœ… Deployment complete."
